# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:


  upload:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # Run npm install & build command
      - name: npm build vite
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm install
      - run: npm run build

      - name: Generate .env file
        env: 
          ENV_VAR: ${{ secrets.PRODUCTION_ENV_VAR }}
        run: |
          # generate .env file with your desired values
          echo "$ENV_VAR" >> .env

      - name: Set environment variables
        run: |
          echo "export $(cat .env | tr '\n' '=')" >> $GITHUB_ENV
      
      - name: Upload repository and env 
        # You may pin to the exact commit or the version.
        # uses: Burnett01/rsync-deployments@45d84ad5f6c174f3e0ffc50e9060a9666d09c16e
        uses: Burnett01/rsync-deployments@6.0.0
        with:
          # The switches
          switches: -avzr --delete --exclude=".git" --exclude=".github"
          # The local path of dir/file will added
          path: /
          # The remote path
          remote_path: /home/${{ secrets.USER }}/laravel-app
           # The remote host
          remote_host: ${{ secrets.HOST }}
          # The remote port
          remote_port: ${{ secrets.PORT }}
          # The remote user
          remote_user: ${{ secrets.USER }}
          # The remote key
          remote_key: ${{ secrets.DEPLOY_KEY }}
          remote_key_pass: ${{ secrets.PASSPHRASE }}
          
  #setup for php,composer and laravel
  laravel-setup:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      
      - name:  install and setup requirement
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            unlink public_html;
            cd laravel-app;
            composer install;
            php artisan key:generate;
            php artisan migrate;
            php artisan db:seed;
            php artisan storage:link;
            cd ../;
            ln -s laravel-app/public public_html
    
      
                
      
            