# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:


  upload:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: update composer and migrations
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            ls;
            cd AbadiComm_Site;
            git pull origin main
            composer install;
            composer update;
            php artisan migrate;
            php artisan config:clear;
            php artisan route:clear;
            php artisan view:clear;
          
    
      
                
      
            